### ISSUE TITLE
Errors in java patterns

### ISSUE THREAD

**Issue by tmoschou** [logstash-plugins/logstash-patterns-core#105]
The patterns
- JAVACLASS
- JAVAFILE
- JAVASTACKTRACEPART

in `patterns/java` are have multiple and non unique definitions. This causes issues for example as the second definition of JAVACLASS (which takes precedence) is defined as

```
JAVACLASS (?:[a-zA-Z0-9-]+\.)+[A-Za-z0-9$]+
```

is wrong. Class qualifiers should be optional and identifiers should be `[a-zA-Z$_][a-zA-Z$_0-9]*` as defined first time.

**Comment by tmoschou** [comment]
Regression introduced in pull request https://github.com/logstash-plugins/logstash-patterns-core/pull/35.

**Comment by kares** [comment]
This has been resolved since - there are no longer any duplicates
