### ISSUE TITLE
Logstash ships with about 120 patterns by default...?

### ISSUE THREAD

**Issue by buddyp450** [logstash-plugins/logstash-patterns-core#111]
Subject is a quote off of https://www.elastic.co/guide/en/logstash/current/plugins-filters-grok.html but I don't see 120 patterns in this repository. Am I missing something?

**Comment by jsvd** [comment]
we call grok pattern a single "NAME" for a regexp pattern or composition of other grok patterns, so

```
logstash-patterns-core (git)-[master] % grep "^[A-Z]" patterns/* | wc -l
     306
```

It should be more like > 300

**Comment by buddyp450** [comment]
Thanks for clarifying.
