### ISSUE TITLE
Mark HOST as breaking change between logstash 1.5.4 and 1.5.5

### ISSUE THREAD

**Issue by ThomasdOtreppe** [logstash-plugins/logstash-patterns-core#118]
After updating my logstash from the repositories from 1.5.4 to 1.5.5, it wouldn't start anymore talking about a pattern %{HOST} not being defined.

After tracking down the change and the help of someone on IRC, it turned out it had been removed.

Could you mark this as a breaking change for 1.5.5 release and check if any other pattern is affected (and mark them as breaking change too)?

Thanks.

**Comment by suyograo** [comment]
@ThomasdOtreppe apologies! this should not be a breaking change, it was unintentional to include this fix in a point release. ref: https://github.com/logstash-plugins/logstash-patterns-core/commit/24cc67919cdf8ab6058e0b1952b6eee501402d88 should only be a 2.0 change. We'll roll back and update this plugin.

**Comment by ThomasdOtreppe** [comment]
Awesome ;)

**Comment by purbon** [comment]
@ThomasdOtreppe this slipped under the radar, thanks for noticing. Will update this soon, in the meanwhile you can also use HOSTNAME, as host was only an alias. No breaking changes should be in the v1 branch, thanks for noticing.

**Comment by suyograo** [comment]
@purbon I got this :)

**Comment by purbon** [comment]
Fixed in https://github.com/logstash-plugins/logstash-patterns-core/pull/120 releasing the new gem soon, will update this issue when done.
