### ISSUE TITLE
duplicate pattern definitions in patterns/java

### ISSUE THREAD

**Issue by rlgomes** [logstash-plugins/logstash-patterns-core#127]
JAVACLASS, JAVAFILE and JAVASTACKTRACEPART are defined twice in that file. I'm sure its not intentional as would be difficult to know which definition was being used at runtime.

**Comment by LionelCons** [comment]
This is still the case currently in master:
```
$ perl -ne 'print("$1\n") if /^(\w+)\s/' * | sort | uniq -c | grep JAVA
      2 JAVACLASS
      2 JAVAFILE
      1 JAVALOGMESSAGE
      1 JAVAMETHOD
      1 JAVASTACKTRACEPART
      1 JAVATHREAD
```

**Comment by LionelCons** [comment]
See also https://github.com/logstash-plugins/logstash-patterns-core/pull/200

**Comment by LionelCons** [comment]
See also https://github.com/logstash-plugins/logstash-patterns-core/issues/105

**Comment by kares** [comment]
closing as duplicate of https://github.com/logstash-plugins/logstash-patterns-core/issues/105 issue has been resolved for a while now
