### ISSUE TITLE
user in COMMONAPACHELOG not matching email address

### ISSUE THREAD

**Issue by wyardley** [logstash-plugins/logstash-patterns-core#141]
I am using nginx, but with NCSA combined format, so think it should match. I believe the 'auth' line in Apache can also be formatted as an email address.

See this example, for instance.
`10.0.0.1 - username@example.com [07/Apr/2016:18:42:24 +0000] "GET /bar/foo/users/1/username%40example.com/authenticate?token=blargh&client_id=15 HTTP/1.1" 400 75 "" "Mozilla/5.0 (iPad; CPU OS 9_3_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13E238 Safari/601.1"`

**Comment by wyardley** [comment]
https://github.com/logstash-plugins/logstash-patterns-core/pull/142

**Comment by magnusbaeck** [comment]
@andrewvc, I believe this issue can be closed.
