### ISSUE TITLE
2.1 Logstash TZ grok pattern doesn't pick up AEST

### ISSUE THREAD

**Issue by woggo85** [logstash-plugins/logstash-patterns-core#147]
The core grok pattern TZ (?:[PMCE][SD]T|UTC) should be
TZ (?:[APMCE][SD]T|UTC) so it picks up Australian Eastern Standard Time.

Cheers

--julian

**Comment by mxhob1** [comment]
PR created for this change.
https://github.com/logstash-plugins/logstash-patterns-core/issues/147

**Comment by andrewvc** [comment]
Merged into master.
