### ISSUE TITLE
EMAILADDRESS pattern is NOT MATCHED 234234234@qq.com

### ISSUE THREAD

**Issue by zacker330** [logstash-plugins/logstash-patterns-core#152]
%{EMAILADDRESS:ident} **NOT MATCHED**   234234234@qq.com
- Version: lastest(2.3.2)
- Operating System:Mac
- Sample Data:234234234@qq.com
- Steps to Reproduce: http://grokconstructor.appspot.com/do/match

**Comment by junho85** [comment]
grok-patterns doesn't allow first character as number.
fixed and made pull request https://github.com/logstash-plugins/logstash-patterns-core/pull/158

**Comment by kares** [comment]
closing with https://github.com/logstash-plugins/logstash-patterns-core/pull/273
