### ISSUE TITLE
logstash pattern for logstash log file?

### ISSUE THREAD

**Issue by mnikhil-git** [logstash-plugins/logstash-patterns-core#186]
Hi,

Is there a pattern file available for the logstash itself? I am htinking of reading logstash logfiles via logstash and was hoping if there is an already available pattern for grok that could help.

**Comment by jordansissel** [comment]
In Logstash 5.0 there is an option to emit logs in a nicely structured JSON format. I recommend you use that and then ingest this log with whatever tooling (logstash, etc) to parse it as JSON.

**Comment by jordansissel** [comment]
Given Logstash 5 has json logging as an option, I'm content not to have any grok patterns for the format. If you want to have a machine read Logstash's logs, JSON format is the way to go.
