### ISSUE TITLE
Add "short" loglevels for Ceph logs

### ISSUE THREAD

**Issue by rlueckl** [logstash-plugins/logstash-patterns-core#187]
Hi,

I noticed that Ceph uses a "short" format for it's loglevel. I've added it manually to my grok-patterns file, but it would be great if it would be in the default file. The short names I've encountered so far are: DBG, INF and WRN.

Proposal:

    -LOGLEVEL ([Aa]lert|ALERT|[Tt]race|TRACE|[Dd]ebug|DEBUG|[Nn]otice|NOTICE|[Ii]nfo|INFO|[Ww]arn?(?:ing)?|WARN?(?:ING)?|[Ee]rr?(?:or)?|ERR?(?:OR)?|[Cc]rit?(?:ical)?|CRIT?(?:ICAL)?|[Ff]atal|FATAL|[Ss]evere|SEVERE|EMERG(?:ENCY)?|[Ee]merg(?:ency)?)
    +LOGLEVEL ([Aa]lert|ALERT|[Tt]race|TRACE|[Dd]ebug|DEBUG|DBG|[Nn]otice|NOTICE|[Ii]nfo|INFO|INF|[Ww]arn?(?:ing)?|WARN?(?:ING)?|WRN|[Ee]rr?(?:or)?|ERR?(?:OR)?|[Cc]rit?(?:ical)?|CRIT?(?:ICAL)?|[Ff]atal|FATAL|[Ss]evere|SEVERE|EMERG(?:ENCY)?|[Ee]merg(?:ency)?)

**Comment by kares** [comment]
Thanks, wonder if anyone else uses these. Seems Ceph specific, probably not worth having these in the re-usable `LOGLEVEL`.

**Comment by rlueckl** [comment]
Hi,

oh wow, this is a 4 year old ticket by me. :) Since nobody else requested this I'm gonna close it. Ceph still uses these Loglevels, which I have in a custom grok-patterns file, but you are right, it's very specific.
