### ISSUE TITLE
SYSLOGTIMESTAMP pattern doesn't match "high precision" timestamps

### ISSUE THREAD

**Issue by joshuaspence** [logstash-plugins/logstash-patterns-core#209]
`rsyslogd` can be configured to write high precision timestamps with `$ActionFileDefaultTemplate RSYSLOG_FileFormat`, but these aren't matched by the `%{SYSLOGTIMESTAMP}` pattern, which only matches `%{MONTH} +%{MONTHDAY} %{TIME}`.

**Comment by AbdulHaseebHussain** [comment]
TIMESTAMP_ISO8601 should match high precision timestamps such as those utilized by rsyslog.

I was able to get a match with the following timestamp:
    
` 2013-10-03T12:28:00.429271-06:00`

**Comment by simmel** [comment]
Yes, use `TIMESTAMP_ISO8601`or even better `SYSLOGBASE2`, see https://github.com/logstash-plugins/logstash-patterns-core/blob/4ba9bf573583ad510aaf4bd0b3418bdbe3402585/patterns/linux-syslog#L3

This can be closed.

**Comment by joshuaspence** [comment]
Ah, perfect. I didn't know about `SYSLOGBASE2. That looks like it should work perfectly.
