### ISSUE TITLE
HTTPD (Apache) combined grok pattern failing due to none interger response code

### ISSUE THREAD

**Issue by tomrade** [logstash-plugins/logstash-patterns-core#214]
Ive noticed that ina  few rare cases in some apache logs I have analysed there log lines when the response code field is "-" , the HTTPD grok pattern expects it always to be %{NUMBER}. Not sure if it should be changed upstream to (?:%{NUMBER}|-), or if it is deemed so rare its a non issue

- Version:
Logstash 6.0 (deb)
Log Line
210.79.229.15 - - [28/Jan/2014:08:59:29 -0600] "GET /template/js/javascript.js?dc=52e7c5c2c4fcc HTTP/1.0" - 0 "REF" "UA"

**Comment by rolandg** [comment]
My solution was to add `-` to the `IPORHOST` pattern in a custom pattern file:

    IPORHOST (?:%{HOSTNAME}|%{IP}|-)

**Comment by kares** [comment]
addressed at https://github.com/logstash-plugins/logstash-patterns-core/pull/282, expected to be available with the 4.2.0 release
