### ISSUE TITLE
why can I not use the grok to define the nginx upstream_addr (HOSTPORT (%{IPV4}:%{POSINT}[, ]{0,2})+)

### ISSUE THREAD

**Issue by auqf** [logstash-plugins/logstash-patterns-core#219]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For all general issues, please provide the following details for fast resolution:

- Version:
- Operating System:
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce:

hi, i use the grok debug to check a single custom express "(?:%{HOSTPORT:upstream_addr}|-)" and express "(%{BASE16FLOAT:upstream_response_time}|-)" is ok, but when i use it with others, it's error.
the logs is"5.9.111.70 - - [24/Jan/2018:11:46:30 +0800] "GET /video/play/2048787.html HTTP/1.1" 200 63563 "-" "Mozilla/5.0 (compatible; MJ12bot/v1.4.8; http://mj12bot.com/)" "-""10.14.129.123:8080""0.086""
the logformat is "log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                       '$status $body_bytes_sent "$http_referer" '
                       '"$http_user_agent" "$http_x_forwarded_for"' '"$upstream_addr"' '"$upstream_response_time"';"
any one can help me

**Comment by kares** [comment]
I am going to close this one as it's been a while since the issue.
in general it's best to ask questions in LogStash [forum](https://discuss.elastic.co/t/logstash/) or maybe also on stack-overflow.
