### ISSUE TITLE
Line 72 in grok-patterns is not optimized

### ISSUE THREAD

**Issue by bcharboneauiherb** [logstash-plugins/logstash-patterns-core#221]
In troubleshooting an issue with parsing of dates, the developer of fluentd-plugins-grok-parser found that the following pattern for "DATE" could use some optimization.

https://github.com/logstash-plugins/logstash-patterns-core/blob/master/patterns/grok-patterns#L72

on Line 72 if it were to be changed to the following it is able to parse a lot more effectively. Issues were found in parsing some US Dates with the current "DATE" pattern

Before:
DATE %{DATE_US}|%{DATE_EU}

After:
DATE (?:%{DATE_US}|%{DATE_EU})

**Comment by jordansissel** [comment]
I can't comment on what fluentd's plugin does, but the grok library implicitly wraps groupings already with `(?:...)` as seen [here](https://github.com/jordansissel/ruby-grok/blob/master/lib/grok-pure.rb#L111):

> could use some optimization

Can you provide data, please? It is difficult to evaluate this claim without data, especially given it appears the grok library already wraps every unnamed capture with `(?:...)` which seems like an automatic version of what your patch provides and seems like this patch is not necessary?

**Comment by jordansissel** [comment]
Testing grok directly from Logstash, this works as expected, I think? This seems like a bug in fluentd (which appears to use an old copy of [grok](https://github.com/jordansissel/ruby-grok/) with some modifications).

Testing:

```
[1] pry(#<LogStash::Runner>)> require "logstash/patterns/core"
equi=> re true
[2] pry(#<LogStash::Runner>)> require "grok-pure"
=> true
[3] pry(#<LogStash::Runner>)> g = Grok.new
...
[4] pry(#<LogStash::Runner>)> Dir.glob(File.join(LogStash::Patterns::Core.path, "*")).each { |f| g.add_patterns_from_file(f) }
...
[5] pry(#<LogStash::Runner>)> g.compile("%{DATE}", true)
...
[6] pry(#<LogStash::Runner>)> puts g.expanded_pattern
(?:(?:(?:(?:0?[1-9]|1[0-2]))[/-](?:(?:(?:0[1-9])|(?:[12][0-9])|(?:3[01])|[1-9]))[/-](?:(?>\d\d){1,2}))|(?:(?:(?:(?:0[1-9])|(?:[12][0-9])|(?:3[01])|[1-9]))[./-](?:(?:0?[1-9]|1[0-2]))[./-](?:(?>\d\d){1,2})))

# Note above, all groups are non-capturing (?:...)
# Let's test the regexp directly and ask it if there are any groups captured at all:
[17] pry(#<LogStash::Runner>)> m = g.instance_variable_get(:@regexp).match("2018-01-01")
=> #<MatchData "18-01-01">
[18] pry(#<LogStash::Runner>)> m.captures
=> []
```

Compiling `%{DATE}` into grok results in 0 captures. This is what I expect. Please follow up with the fluentd grok authors to find out what they are doing -- I believe your concern can be resolved with them.
