### ISSUE TITLE
SuSE Firewall 2, does not return the date / time of the log entry.

### ISSUE THREAD

**Issue by dwbenjamin** [logstash-plugins/logstash-patterns-core#227]
logstash-patterns-core-4.1.2

SFW2 should return log entry date.

fixes https://github.com/logstash-plugins/logstash-patterns-core/pull/228

**Comment by kares** [comment]
Thanks for the report David, this is expected to be resolved at https://github.com/logstash-plugins/logstash-patterns-core/pull/293
