### ISSUE TITLE
代表国人留个言

### ISSUE THREAD

**Issue by 51centos** [logstash-plugins/logstash-patterns-core#234]

**Comment by yaauie** [comment]
Issue title translates to:

> Representing the people of the country

I believe this pull-request was opened unintentionally, so I am closing it.

if you have an issue with clear reproduction steps, please feel free to open a new issue including a full description of your problem.

Automated translation via translate.google.com:

> 我相信这个拉动请求是无意中打开的，所以我正在关闭它。
> 如果您有明确的复制步骤问题，请随时打开一个新问题，包括问题的完整描述。
