### ISSUE TITLE
HTTPD_COMBINEDLOG pattern conflicts with ECS v1.0

### ISSUE THREAD

**Issue by C-Duv** [logstash-plugins/logstash-patterns-core#243]
The `HTTPD_COMBINEDLOG` pattern creates a `agent` field which conflicts with [the `agent` field of ECS 1.0](https://github.com/elastic/ecs/blob/1.0/fields.yml#L8).

**Comment by hume-github** [comment]
I'm running into this as well.  I'd propose renaming the match to "useragent", and I will in my own configuration, but I'm not sure what kind of downstream effects that'll have.

**Comment by holiiveira** [comment]
any workaround for this?

**Comment by tcassaert** [comment]
What I've done is replacing the HTTPD_COMBINEDLOG pattern with `%{HTTPD_COMMONLOG} %{QS:referrer} %{QS:client_agent}`. This avoids having a conflicting `agent` field.

**Comment by danlsgiga** [comment]
Faced the same issue and used the workaround @tcassaert suggested. I'd suggest to have the `agent` changed to `useragent`
