### ISSUE TITLE
Should the SPACE grok pattern match zero or more?

### ISSUE THREAD

**Issue by zestysoft** [logstash-plugins/logstash-patterns-core#245]
I noticed that the SPACE grok pattern is currently set to:

> SPACE \s*

If it is meant to match whitespace, shouldn't it have a starting point where it matches at least one character?  Something like:

> SPACE \s+

I've ran into a situation where this pattern was skipped because it allows matching zero spaces.

**Comment by kares** [comment]
you're right but at this point changing the behavior would be a breaking change, 
still LS allows using pattern overrides ... if anyone is unhappy with `SPACE` behavior

**Comment by zestysoft** [comment]
I don't use LS anymore
