### ISSUE TITLE
As a sysadmin, I'd like to have shorewall logs on firewall default grok patterns

### ISSUE THREAD

**Issue by mdelapenya** [logstash-plugins/logstash-patterns-core#25]
I've read this issue on Jira (https://logstash.jira.com/browse/LOGSTASH-491), but could not replicate the pattern, as the patterns are not present anywhere, such as IPTABLESCHAIN, SPORT...).

As shorewall is a vey popular open source firewall product, could it be possible to add a pattern to filter its logs?

Thanks!

PS: This could be an example of a log line in Shorewall, which follows http://logi.cc/en/2010/07/netfilter-log-format to define the log format

```
Apr 16 08:26:46 myHostName kernel: [5595162.268034] Shorewall:net2fw:DROP:IN=eth1 OUT= MAC=myMacAddress SRC=sourceIP DST=destinyIP LEN=48 TOS=0x00 PREC=0x00 TTL=114 ID=25671 DF PROTO=TCP SPT=10884 DPT=43406 WINDOW=8192 RES=0x00 SYN URGP=0
```

**Comment by purbon** [comment]
Hi @mdelapenya, as you have experience with this log format, it would be great if you can create a PR with this improvement, you can take inspiration for example with what has been done with the mongodb. Are you in?
