### ISSUE TITLE
Grok Filter Application

### ISSUE THREAD

**Issue by omarals95** [logstash-plugins/logstash-patterns-core#252]
I finally got the parsing to work but im trying to put it in the conf file for logstash.

I get two cisco asa messages and therefore have to filters, how do  get it to filter the messages? Its supposed to filter Cisco ASA 106023 and 106100 messages

[Logstash conf.txt](https://github.com/logstash-plugins/logstash-patterns-core/files/3935090/Logstash.conf.txt)

I have attached the conf file. if anyone knows how to fix it please let me know.

**Comment by kares** [comment]
seems this is not an issue report, would advice to rather use forums or stack-overflow for questions.
