### ISSUE TITLE
grok patterns for firewall checkpoint helpme!

### ISSUE THREAD

**Issue by dcantos1** [logstash-plugins/logstash-patterns-core#309]
Hi everyone,

I'm new to this and I'm wanting to parse the following log for a firewall checkpoint, I don't know if you can help me.

-5:00 192.168.1.2 Action="accept" UUid="{0x61b22d19,0x4,0xf1137d7f,0xc0000000}" inzone="Internal" outzone="Internal" src="10.207.104.247" dst="10.207.106.9" proto="6" xlatesrc="186.5.16.83" NAT_rulenum="14" NAT_addtnl_rulenum="1" rule="21 (Incoming/Internal)" product="VPN-1 & FireWall-1" service="10050" s_port="38930

**Comment by kares** [comment]
closing as not an issue, please try the [discuss forum](https://discuss.elastic.co/c/elastic-stack/logstash/14) or stack-overflow next time ...
