### ISSUE TITLE
Support german month names

### ISSUE THREAD

**Issue by cniweb** [logstash-plugins/logstash-patterns-core#34]
In line 48:
https://github.com/logstash-plugins/logstash-patterns-core/blob/master/patterns/grok-patterns#L48
Support month name in german, please.

**Comment by purbon** [comment]
@cniweb that would be very nice, are you willing to contribute some samples and might be a regular expression for that?

**Comment by cniweb** [comment]
@purbon OK, i add the pattern. It´s OK?

**Comment by purbon** [comment]
Go ahead and open a PR for that,
   do you know there is a way to add test for patterns? check the specs dir
for details. When adding the pattern keep in mind to add also some test for
it :-)

let me know if you encounter issues.

/purbon

On Thursday, May 7, 2015, Christian Häussler <notifications@github.com>
wrote:

> @purbon <https://github.com/purbon> OK, i add the pattern. It´s OK?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/logstash-plugins/logstash-patterns-core/issues/34#issuecomment-99741329>
> .
>


-- 
Pere Urbon-Bayes
Software Engineer
https://www.elastic.co
https://twitter.com/purbon

**Comment by cniweb** [comment]
Fixed with https://github.com/logstash-plugins/logstash-patterns-core/issues/35
