### ISSUE TITLE
AWS ELB log regex doesn't support SSL cipher/protocol

### ISSUE THREAD

**Issue by aodj** [logstash-plugins/logstash-patterns-core#73]
The [AWS ELB format spec](https://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/access-log-collection.html) includes SSL cipher and SSL protocol fields that aren't parsed by the currently available `ELB_ACCESS_LOG` regex.

**Comment by purbon** [comment]
Thanks for your feedback @aodj, are you willing to contribute this patterns back? Do you know/have example logs to write the test for this patterns? I guess we might also use the ones in the spec.

 /cheers

**Comment by salexpdx** [comment]
I came across the same issue this evening and am working on a fix for it tonight

**Comment by salexpdx** [comment]
Hi @purbon, I filled out the CLA a few days ago but haven't seen this get merged so wanted to post a comment here letting you know it was done.

**Comment by kares** [comment]
this should be addressed with https://github.com/logstash-plugins/logstash-patterns-core/pull/287, if we missed something please open a new issue with the specifics
