### ISSUE TITLE
Release often : I'm eager to use new pattern and no new gem

### ISSUE THREAD

**Issue by smougenot** [logstash-plugins/logstash-patterns-core#76]
Hi, 
It would be nice if you released a new version of the gem : there are a lot of new patterns since 1.10.
Please!!

In my particular case migrating from Logstash 1.4 to 1.5 is hurting due to pattern abductions (maybe aliens doing again).

**Comment by purbon** [comment]
yay! I will do a new release soon!

**Comment by purbon** [comment]
Enjoy https://rubygems.org/gems/logstash-patterns-core !
