### ISSUE TITLE
logstash 1.5.3 on windows won't read custom patterns in grok{ patterns_dir

### ISSUE THREAD

**Issue by nickak** [logstash-plugins/logstash-patterns-core#78]
Hi,

logstash 1.5.3 on windows won't read custom patterns file
I use patterns_dir
grok{
patterns_dir => "C:/devtools/logstash-1.5.3/patterns"

it works only when I put the patterns file in 
C:\devtools\logstash-1.5.3\vendor\bundle\jruby\1.9\gems\logstash-patterns-core-0.1.10\patterns

best regards

**Comment by HavoCc** [comment]
Hi *,

I encountered the same issue. Has there been any progress yet?
Or is this already fixed but the ticket is still open?

kind regards

**Comment by jasperdj** [comment]
Same issue here.

**Comment by kares** [comment]
this seems to have been an issue with the grok filter, expected to be working now
